### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by ghost** [cisco/libusnic_verbs#2]
Please add a file "COPYING", which should contain the complete text of GPLv2. It is necessary for importing libusnic_verbs into Fedora. Thanks.

**Comment by jsquyres** [comment]
Mmm... yes, I see that our `LICENSE` file makes reference to a `COPYING` file that doesn't exist.  Doh!

I'm happy to add the complete text of the GPLv2.

Question: can I add the GPLv2 text to `LICENSE`, or does the file need to be named `COPYING`?  (I don't really care what the final file is named; I'm more asking if it matters / if you have a preference)

**Comment by jsquyres** [comment]
@HonggangLI v2.0.2 has been released with a new `COPYING` file with both the BSD and GPLv2 license: https://github.com/cisco/libusnic_verbs/releases/tag/v2.0.2

**Comment by ghost** [comment]
Rebuild the rpm with v2.0.2. Thank you!
https://bugzilla.redhat.com/show_bug.cgi?id=1327071#c7
