### ISSUE TITLE
Building RPM from libusnic_verbs-2.0.2.tar.bz2 fails

### ISSUE THREAD

**Issue by martinkontsek** [cisco/libusnic_verbs#6]
We have found out a problem with the RPM build from the tarball `libusnic_verbs-2.0.2.tar.bz2` using `libusnic_verbs.spec` file inside this tarball. The regular build of the tarball `./configure && make` is fine. Here is the error message:

`rpmbuild -ba libusnic_verbs.spec`
`...`
`cp: cannot stat 'LICENSE': No such file or directory`
`error: Bad exit status from /var/tmp/rpm-tmp.kK7HuQ (%doc)`

See attachment for full log. [libusnic_verbs-2.0.2_RPMbuildError.txt](https://github.com/cisco/libusnic_verbs/files/562946/libusnic_verbs-2.0.2_RPMbuildError.txt)

This is caused by the fact that rpmbuild is expecting to find `README` and `LICENSE` files in the tarball (line `%doc AUTHORS LICENSE README` in the `libusnic_verbs.spec`) but they are not present in the tarball.

**Comment by jsquyres** [comment]
@martinkontsek Thanks for the report.  It looks like I had already fixed these issues, but not done a new release.  Doh!  I've now released v2.0.3 which should fix these issues: https://github.com/cisco/libusnic_verbs/releases/tag/v2.0.3.
